### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by df8oe** [rellit/resol-vbus-python#12]
I am working with Resol-MX and LAN connection using Python3 (You can look at my fork on my repository). I have strange behaviour that would impact using the script for getting data for a time database...

When I call the script it seems to be "by chance" if I get data of 0x7e11 DeltaSol MX [Regler] or of 0x7e21 DeltaSol MX [Heizkreis 1]. Sometimes I get data of "Regler", sometimes of "Heizkreis1". I already have switched to debug but I am unable to identify the problem. I attach both logs. Can you identify what is going wrong?
[resol-py_Regler.txt](https://github.com/rellit/resol-vbus-python/files/10365854/resol-py_Regler.txt)
[resol-py_Heizkreis1.txt](https://github.com/rellit/resol-vbus-python/files/10365856/resol-py_Heizkreis1.txt)

**Comment by 99technetium** [comment]
did you try to increase the number of [`expected_packets`](https://github.com/rellit/resol-vbus-python/blob/840173b3509287ab78b3e98e19ef64eb0167c990/config.py#L20)? I'm pretty new to vbus but it looks like "Regler" and "Heizkreis" are treated as multiple devices and hence packets.

**Comment by df8oe** [comment]
Thank you for this hint. I have increased number of expected packages and now it is working stable. The reason I was not stumbled over this value was that it sometimes worked before - without changing anything. Very interesting behaviour :)
